defaults:
  - default
  - components/sequence
  - components/md
  #- components/struct_graph
  - components/pocket
  - components/text
  - components/struct_token
  #- components/msa

loss_fn: CLIP
local_loss: true
gather_with_grad: true
use_l1_regularization: true
train_on_all_modalities_after_step: 0